# Build arguments
ARG SOURCE_CODE=.

# Build the manager binary
FROM registry.redhat.io/ubi8/go-toolset:1.26.7-1790750376@sha256:1439433a2cd76f0c20035001d46074e85a59ccd0d318a16023c3fd9fdd18ddf5 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

# Build
USER root
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go

FROM registry.redhat.io/ubi8/ubi-minimal@sha256:a2006dac3089997a79cb2d211a80ac59949d18f16e48bb89849fb96efabb970b AS runtime

ARG USER=2000

LABEL com.redhat.component="odh-model-controller-container" \
      name="managed-open-data-hub/odh-model-controller-rhel8" \
      description="The controller removes the need for users to perform manual steps when deploying their models" \
      summary="odh-model-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-model-controller" \
      io.k8s.description="odh-model-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

WORKDIR /
COPY --from=builder /workspace/manager .
USER ${USER}

ENTRYPOINT ["/manager"]
